ComputerNet.WEB/Controllers/ComputerController.cs
using AutoMapper;
using ComputerNet.BLL.DTO;
using ComputerNet.BLL.Interfaces;
using ComputerNet.WEB.Models;
using System.Web.Mvc;

namespace ComputerNet.WEB.Controllers
{
    [Authorize]
    public class ComputerController : GenericController<ComputerDTO, ComputerVM>
    {
        public ComputerController(IMapper mapper, IGenericService<ComputerDTO> service) : base(mapper, service)
        {
        }

    }
}

ComputerNet.WEB/Controllers/NetworkController.cs
using AutoMapper;
using ComputerNet.BLL.DTO;
using ComputerNet.BLL.Interfaces;
using ComputerNet.WEB.Models;
using System.Web.Mvc;

namespace ComputerNet.WEB.Controllers
{
    [Authorize]
    public class NetworkController : Controller
    {
        private readonly IGenericService<ComputerDTO> _computerService;
        private readonly IGenericService<RouterDTO> _routerService;
        private readonly INetworkService _networkService;
        private readonly IMapper _mp;

        public NetworkController(IMapper mapper, IGenericService<ComputerDTO> computerService,
                                 IGenericService<RouterDTO> routerService, INetworkService networkService)
        {
            _computerService = computerService;
            _routerService = routerService;
            _networkService = networkService;
            _mp = mapper;
        }
     
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var computerDTO = _computerService.GetById(id.Value);
            var computerVM = _mp.Map<ComputerVM>(computerDTO);  

            return View(computerVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(int? id, long logicAddress)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var oldComputerDTO = _computerService.GetById(id.Value);
            var routerDTO = _routerService.GetById(oldComputerDTO.RouterId.Value);

            if (!_networkService.CheckIPRange(id.Value, logicAddress))
            {
                var computerVM = _mp.Map<ComputerVM>(oldComputerDTO);

                ModelState.AddModelError("", "Ip is out of range!");
                return View(computerVM);            
            }

            _computerService.Update(new ComputerDTO {
                Model = oldComputerDTO.Model,
                HardwareAddress = oldComputerDTO.HardwareAddress,
                Id = oldComputerDTO.Id,
                Manufactured = oldComputerDTO.Manufactured,
                RoomId = oldComputerDTO.RoomId,
                RouterId = oldComputerDTO.RouterId,
                LogicAddress = logicAddress,
                Mask = routerDTO.Mask
            });

            return RedirectToAction("Index", "Computer");
        }
    }
}

ComputerNet.WEB/Views/Computer/Create.cshtml
@model ComputerNet.WEB.Models.ComputerVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ComputerVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufactured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufactured, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufactured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogicAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogicAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogicAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mask, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mask, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mask, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HardwareAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HardwareAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HardwareAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RouterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RouterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RouterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ComputerNet.WEB/Views/Computer/Delete.cshtml
@model ComputerNet.WEB.Models.ComputerVM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ComputerVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufactured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufactured)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LogicAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogicAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mask)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mask)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HardwareAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HardwareAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RouterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RouterId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ComputerNet.WEB/Views/Computer/Edit.cshtml
@model ComputerNet.WEB.Models.ComputerVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ComputerVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufactured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufactured, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufactured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogicAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogicAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogicAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mask, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mask, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mask, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HardwareAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HardwareAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HardwareAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RouterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RouterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RouterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ComputerNet.WEB/Views/Computer/Index.cshtml
@model IEnumerable<ComputerNet.WEB.Models.ComputerVM>

@{
    ViewBag.Title = "Computers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufactured)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogicAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mask)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HardwareAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RouterId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Manufactured)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogicAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mask)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HardwareAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RouterId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |           
            @Html.ActionLink("Set IP", "Index", "Network", new { id = item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>