ComputerNet.WEB/Controllers/BuildingController.cs
using AutoMapper;
using ComputerNet.BLL.DTO;
using ComputerNet.BLL.Interfaces;
using ComputerNet.WEB.Models;
using System.Web.Mvc;

namespace ComputerNet.WEB.Controllers
{
    [Authorize]
    public class BuildingController : GenericController<BuildingDTO, BuildingVM>
    {
        public BuildingController(IMapper mapper, IGenericService<BuildingDTO> service) : base(mapper, service)
        {
        }
    }
}

ComputerNet.WEB/Controllers/DeviceController.cs
using AutoMapper;
using ComputerNet.BLL.Interfaces;
using ComputerNet.WEB.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ComputerNet.WEB.Controllers
{
    [Authorize]
    public class DeviceController : Controller
    {
        private readonly IDeviceService _service;
        private readonly IMapper _mp;

        public DeviceController(IMapper mapper, IDeviceService service)
        {
            _service = service;
            _mp = mapper;
        }

        public ActionResult Index(IEnumerable<DeviceVM> devices)
        {
            return View(devices);
        }

        [ValidateAntiForgeryToken]
        public ActionResult SearchByLogicAddress(long LogicAddress) 
        {
            var devicesDTO = _service.SearchByLogicAddress(LogicAddress);
            var devicesVM = _mp.Map<IEnumerable<DeviceVM>>(devicesDTO);

            return View("Index", devicesVM);
        }

        [ValidateAntiForgeryToken]
        public ActionResult SearchByHardwareAddress(string HardwareAddress) 
        {
            var deviceDTO = _service.SearchByHardwareAddress(HardwareAddress);
            var deviceVM = _mp.Map<DeviceVM>(deviceDTO);

            return View("Index", new List<DeviceVM> { deviceVM } );
        }

        [ValidateAntiForgeryToken]
        public ActionResult SearchByModel(string Model)
        {
            var devicesDTO = _service.SearchByModel(Model);
            var devicesVM = _mp.Map<IEnumerable<DeviceVM>>(devicesDTO);

            return View("Index", devicesVM);
        }

        [ValidateAntiForgeryToken]
        public ActionResult SearchByManufactureDate(DateTime Manufactured) 
        {
            var devicesDTO = _service.SearchByManufactureDate(Manufactured);
            var devicesVM = _mp.Map<IEnumerable<DeviceVM>>(devicesDTO);

            return View("Index", devicesVM);
        }

        [ValidateAntiForgeryToken]
        public ActionResult SearchByRoomNumber(int Number) 
        {
            var devicesDTO = _service.SearchByRoomNumber(Number);
            var devicesVM = _mp.Map<IEnumerable<DeviceVM>>(devicesDTO);

            return View("Index", devicesVM);
        }

        [ValidateAntiForgeryToken]
        public ActionResult SearchByBuildingName(string Name)
        {
            var devicesDTO = _service.SearchByBuildingName(Name);
            var devicesVM = _mp.Map<IEnumerable<DeviceVM>>(devicesDTO);

            return View("Index", devicesVM);
        }
    }
}

ComputerNet.WEB/Controllers/RoomController.cs
using AutoMapper;
using ComputerNet.BLL.DTO;
using ComputerNet.BLL.Interfaces;
using ComputerNet.WEB.Models;
using System.Web.Mvc;

namespace ComputerNet.WEB.Controllers
{
    [Authorize]
    public class RoomController : GenericController<RoomDTO, RoomVM>
    {
        public RoomController(IMapper mapper, IGenericService<RoomDTO> service) : base(mapper, service)
        {
        }

    }
}

ComputerNet.WEB/Controllers/RouterController.cs
using AutoMapper;
using ComputerNet.BLL.DTO;
using ComputerNet.BLL.Interfaces;
using ComputerNet.WEB.Models;
using System.Web.Mvc;

namespace ComputerNet.WEB.Controllers
{
    [Authorize]
    public class RouterController : GenericController<RouterDTO, RouterVM>
    {
        public RouterController(IMapper mapper, IGenericService<RouterDTO> service) : base(mapper, service)
        {
        }
    }
}

ComputerNet.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>     
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light border-bottom">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link text-info" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Buildings", "Index", "Building", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Computers", "Index", "Computer", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Rooms", "Index", "Room", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Routers", "Index", "Router", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Search devices", "Index", "Device", null, new { @class = "nav-link" })
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (User.Identity.IsAuthenticated)
            {
            <li class="nav-item dropdown">
                <div class="navbar-text dropdown-toggle" id="navbardrop" data-toggle="dropdown">Account: @User.Identity.Name</div>
                <div class="dropdown-menu dropdown-menu-right">
                    @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "dropdown-item" })
                </div>
            </li>
            }
            else 
            {
            <li class="nav-item">
                @Html.ActionLink("Login here", "Login", "Account", null, new { @class = "nav-link" })
            </li>            
            }
        </ul>
    </nav>
    <div class="p-5">
        @RenderBody()  
    </div>
</body>
</html>